Adding version flag
packagemgmt/repositorytools pull request #31
Opened 2017-07-08 09:01 UTC by Lucas-C

2017-07-10 06:51 UTC, stardust85 requested changes
Please fix the Python 2.x compatibility of your change and then I can merge it.

2017-07-10 06:51 UTC, stardust85 commented on repositorytools/cli/common.py
> +        self.parser.add_argument("-V", action="store_true", dest="display_version", help="Prints version and exit")
please add also long form `--version` if you want is as an option.

2017-07-10 06:51 UTC, stardust85 commented on repositorytools/cli/common.py
> +        if args_namespace.display_version:
This functionality didn't work for me in Python 2.6 or 2.7 for some reason. It exited, but didn't print anything.

 Please try a solution working also in python >= 2.6

2017-07-10 06:51 UTC, stardust85 commented on repositorytools/cli/common.py
> +        self.run(*args)
Merged in #30, but you can probably keep it here, because github doesn't complain about it ;)

2017-07-10 09:50 UTC, Lucas-C commented on repositorytools/cli/common.py
> +        self.parser.add_argument("-V", action="store_true", dest="display_version", help="Prints version and exit")
Not possible sadly, you already used that flag:
https://github.com/stardust85/repositorytools/blob/master/repositorytools/cli/commands/artifact.py#L30

2017-07-10 10:16 UTC, Lucas-C commented on repositorytools/cli/common.py
> +        if args_namespace.display_version:
It works for me with Python 2.7, but you have to feed the subparser:
```$ artifact -V get-metadata X Y
repositorytools v4.2.2
```
This is due to a bug / change in `argparse` between Python 2 & 3: https://stackoverflow.com/a/24211480/636849
I haven't found any easy workaround so far. The error is raised here: https://github.com/python/cpython/blob/2.7/Lib/argparse.py#L1949

2017-07-10 10:17 UTC, Lucas-C commented on repositorytools/cli/common.py
> +        self.run(*args)
Yes, that was expected. I left this commit so that this `adding_version_flag` branch could be merged once you included the `*args` fix.

2017-07-10 10:21 UTC, Lucas-C commented on repositorytools/cli/common.py
> +        if args_namespace.display_version:
If you don't like this behaviour, feel free to ignore this PR, and potentially include this feature by yourself later on.
This commit was only planned as a minor improvement, I don't think it's worth a convoluted workaround :)

2017-12-15 13:56 UTC, Lucas-C commented
I rebased this PR. Is this ok for you ?

2017-12-20 00:52 UTC, stardust85 commented
Hi, please merge my changes from today to your branch. They fix broken python2.6 and python 3.3 tests. Btw, would you mind if I gave you ownership of repositorytools? :)

2017-12-20 07:15 UTC, Lucas-C commented
Done

2017-12-20 08:22 UTC, merged

2017-12-20 08:48 UTC, stardust85 commented
OK, I sent you an invitation to packagemanagement organization.